[tool.poetry]
name = "langchain"
version = "0.0.0"
description = "Building applications with LLMs through composability"
authors = []
license = "MIT"
readme = "README.md"
repository = "https://www.github.com/hwchase17/langchain"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
pydantic = "^1.10.2"
SQLAlchemy = "^1.4.44"
requests = "^2.28.1"
PyYAML = "^6.0"
numpy = "^1.22.0"
faiss-cpu = {version = "^1.7.3", optional = true}
wikipedia = {version = "^1.4.0", optional = true}
elasticsearch = {version = "^8.5.2", optional = true}
manifest-ml = {version = "^0.0.1", optional = true}
spacy = {version = "^3.4.3", optional = true}
nltk = {version = "^3.7", optional = true}
transformers = {version = "^4.25.1", optional = true}

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-dotenv = "^0.5.2"

[tool.poetry.group.lint.dependencies]
flake8-docstrings = "^1.6.0"
black = "^22.10.0"
isort = "^5.10.1"
flake8 = "^6.0.0"

[tool.poetry.group.typing.dependencies]
mypy = "^0.991"
types-pyyaml = "^6.0.12.2"
types-requests = "^2.28.11.5"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
playwright = "^1.28.0"

[tool.poetry.extras]
llms = ["cohere", "openai", "nlpcloud", "huggingface_hub", "manifest-ml"]
all = ["cohere", "openai", "nlpcloud", "huggingface_hub", "manifest-ml", "elasticsearch", "google-search-results", "faiss-cpu", "sentence_transformers", "transformers", "spacy", "nltk", "wikipedia"]

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = "True"
disallow_untyped_defs = "True"
exclude = ["notebooks"]

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
